import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Slate-ai-powered-dashboard",
  description: "Generated by Anju",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
      </body>
    </html>
  );
}
